USE ROLE ACCOUNTADMIN;

-- CREATE DATABASE AND SCHEMAS
CREATE DATABASE IF NOT EXISTS AIRLINE_DWH;
USE DATABASE AIRLINE_DWH;

CREATE SCHEMA IF NOT EXISTS STAGE_1_RAW;
CREATE SCHEMA IF NOT EXISTS STAGE_2_CORE;
CREATE SCHEMA IF NOT EXISTS STAGE_3_ANALYTICS;

CREATE OR REPLACE FILE FORMAT STAGE_1_RAW.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'NaN', '')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE TABLE STAGE_1_RAW.RAW_FLIGHTS (
    INDEX_COL STRING,
    PASSENGER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    GENDER STRING,
    AGE STRING,
    NATIONALITY STRING,
    AIRPORT_NAME STRING,
    AIRPORT_COUNTRY_CODE STRING,
    COUNTRY_NAME STRING,
    AIRPORT_CONTINENT STRING,
    CONTINENTS STRING,
    DEPARTURE_DATE STRING,
    ARRIVAL_AIRPORT STRING,
    PILOT_NAME STRING,
    FLIGHT_STATUS STRING,
    TICKET_TYPE STRING,
    PASSENGER_STATUS STRING
);

CREATE OR REPLACE STREAM STAGE_1_RAW.FLIGHTS_STREAM 
    ON TABLE STAGE_1_RAW.RAW_FLIGHTS;

CREATE OR REPLACE TABLE STAGE_2_CORE.FACT_FLIGHTS (
    PASSENGER_ID VARCHAR,
    FULL_NAME VARCHAR,
    GENDER VARCHAR,
    AGE NUMBER,
    NATIONALITY VARCHAR,
    AIRPORT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR
);

CREATE OR REPLACE TABLE STAGE_2_CORE.AUDIT_LOG (
    LOG_ID INT AUTOINCREMENT,
    PIPELINE_NAME VARCHAR,
    TABLE_NAME VARCHAR,
    AFFECTED_ROWS NUMBER,
    EXECUTION_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE STAGE_3_ANALYTICS.DAILY_AIRLINE_STATS (
    FLIGHT_STATUS VARCHAR,
    TOTAL_PASSENGERS NUMBER,
    AVG_AGE FLOAT
);

CREATE OR REPLACE PROCEDURE STAGE_1_RAW.LOAD_RAW_DATA()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Using DELETE instead of TRUNCATE to avoid Airflow transaction errors
    DELETE FROM STAGE_1_RAW.RAW_FLIGHTS;
    
    -- FORCE = TRUE ensures the file is reloaded even if Airflow triggers it again
    COPY INTO STAGE_1_RAW.RAW_FLIGHTS
    FROM @STAGE_1_RAW.AIRLINE_STAGE/flights.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGE_1_RAW.CSV_FORMAT')
    FORCE = TRUE;
    
    RETURN 'Data loaded successfully into RAW table!';
END;
$$;

CREATE OR REPLACE PROCEDURE STAGE_2_CORE.PROCESS_CORE_DATA()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    inserted_rows INTEGER;
BEGIN
    INSERT INTO STAGE_2_CORE.FACT_FLIGHTS
    SELECT 
        PASSENGER_ID,
        FIRST_NAME || ' ' || LAST_NAME,
        GENDER,
        TRY_CAST(AGE AS NUMBER),
        NATIONALITY,
        AIRPORT_NAME,
        FLIGHT_STATUS
    FROM STAGE_1_RAW.FLIGHTS_STREAM
    WHERE METADATA$ACTION = 'INSERT';
    
    inserted_rows := SQLROWCOUNT;
    
    -- Log the execution details
    INSERT INTO STAGE_2_CORE.AUDIT_LOG (PIPELINE_NAME, TABLE_NAME, AFFECTED_ROWS)
    VALUES ('LOAD_STAGE_2', 'FACT_FLIGHTS', :inserted_rows);
    
    RETURN 'Data loaded into CORE table. Inserted rows: ' || :inserted_rows;
END;
$$;

CREATE OR REPLACE PROCEDURE STAGE_3_ANALYTICS.PROCESS_ANALYTICS_DATA()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    inserted_rows INTEGER;
BEGIN
    -- Clear old stats before calculating new ones
    DELETE FROM STAGE_3_ANALYTICS.DAILY_AIRLINE_STATS;
    
    INSERT INTO STAGE_3_ANALYTICS.DAILY_AIRLINE_STATS
    SELECT 
        FLIGHT_STATUS,
        COUNT(PASSENGER_ID) AS TOTAL_PASSENGERS,
        AVG(AGE) AS AVG_AGE
    FROM STAGE_2_CORE.FACT_FLIGHTS
    GROUP BY FLIGHT_STATUS;
    
    inserted_rows := SQLROWCOUNT;
    
    -- Log the execution details
    INSERT INTO STAGE_2_CORE.AUDIT_LOG (PIPELINE_NAME, TABLE_NAME, AFFECTED_ROWS)
    VALUES ('LOAD_STAGE_3', 'DAILY_AIRLINE_STATS', :inserted_rows);
    
    RETURN 'Data loaded into ANALYTICS table. Inserted rows: ' || :inserted_rows;
END;
$$;